version: "3.8"
services:
  api:
    image: go-example
    container_name: api
    build: .
    env_file:
      - ./.env.docker
    volumes:
      - .:/tmp/src/app:cached
    restart: always
    ports:
      - 8855:8855
  db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - .docker/data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
